# Generated by Django 5.0.1 on 2024-03-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
