"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xxta((n3gwm!n^+p@7a)!chs#_27#h+1tu^4xo9a5wweg%)oyv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", ".vercel.app", 'localhost', '127.0.0.1',]


'''
to get the LOGIN password code. we need to follow the steps below....

1. open gmail settings -> more settins -> Forwarding and POP/IMAP -> Enable IMAP -> save changes
2. turn on the 2 step verification 
3. search app passwords in google account.. -> create app -> and create code -> 
    copy the code and use it as password..

    mailID --> koradamahesh2000@gmail.com
    password --> eoolrwwlumzzefaw
'''


# Email HAndlings...

# Configure email backend settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # SMTP server hostname or IP address
EMAIL_PORT = 587  # Port number for the SMTP server (587 for TLS, 465 for SSL)
EMAIL_USE_TLS = True  # Use TLS (Transport Layer Security) encryption
EMAIL_HOST_USER = 'koradamahesh2000@gmail.com'  # Your SMTP username (if required)
EMAIL_HOST_PASSWORD = 'eoolrwwlumzzefaw'  # Your SMTP password (if required)
EMAIL_USE_SSL = False  # Set it to True if you're using SSL instead of TLS

# Default sender email address
# DEFAULT_FROM_EMAIL = 'koradamahesh2000@gmail.com'


# adding this for login management using (email and password) instead of (username and password)
AUTHENTICATION_BACKENDS = ['auth_accounts.custom_auth_backends.EmailAuthBackend']

# Captcha settings
CAPTCHA_LENGTH = 6 # Set the length of captcha

# GOOGLE_RECAPTCHA_PUBLIC_KEY = '6Lf7PbQpAAAAAOqV5WM1hZXahVex89RXgjHioQyq'
GOOGLE_RECAPTCHA_SECRET_KEY = '6Lf7PbQpAAAAAElFeNQK2tJY-g4wBxoOzt_o2cU6'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.staticfiles.finders.FileSystemFinder',

    'store',
    'auth_accounts',
    'admin_access',

    'captcha',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR/ 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR /'static',

]

MEDIA_URL = '/images/'

MEDIA_ROOT = BASE_DIR/ 'static/storeimages'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
